spring.application.name=cart-service

server.port=${PORT:0}

eureka.client.service-url.defaultZone=https://eureka-server-nzb0.onrender.com/eureka
spring.jpa.hibernate.ddl-auto= update



spring.datasource.url = jdbc:postgresql://dpg-d4b6oure5dus73efdc0g-a.oregon-postgres.render.com/products_9z2s?sslmode=require
spring.datasource.username= products_9z2s_user
spring.datasource.password= eY5oktPT9YKLXG7VFGRJCnfN3PoXNvI1
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size= 5